#!/bin/sh
MYSELF=`which "$0" 2>/dev/null`
[ $? -gt 0 -a -f "$0" ] && MYSELF="./$0"
java=java
if test -n "$JAVA_HOME"; then
    java="$JAVA_HOME/bin/java"
fi
exec "$java" $java_args -jar $MYSELF "$@"
exit 1

## use cat bash_run.sh snpdist.jar > snpdist.run && chmod +x snpdist.run
## E.G. cat bash_run.sh snpdistjava-0.3.0.jar > snpdist.run && chmod +x snpdist.run
## to append the runnable jar to the end of this jar, making it runnable from the
## unix command line without invoking java -jar ... explicitly
